# Catppuccin Mocha
#gui:
# theme:
#  activeBorderColor:
#    - '#f2cdcd'
#    - bold
#  inactiveBorderColor:
#    - '#a6adc8'
#  optionsTextColor:
#    - '#89b4fa'
#  selectedLineBgColor:
#    - '#313244'
#  cherryPickedCommitBgColor:
#    - '#45475a'
#  cherryPickedCommitFgColor:
#    - '#f2cdcd'
#  unstagedChangesColor:
#    - '#f38ba8'
#  defaultFgColor:
#    - '#cdd6f4'
#  searchingActiveBorderColor:
#    - '#f9e2af'
#
#authorColors:
#  '*': '#b4befe'

# Catppuccin Latte
gui:
 theme:
  activeBorderColor:
    - '#dd7878'
    - bold
  inactiveBorderColor:
    - '#8c8fa1'
  optionsTextColor:
    - '#1e66f5'
  selectedLineBgColor:
    - '#ccd0da'
  cherryPickedCommitBgColor:
    - '#bcc0cc'
  cherryPickedCommitFgColor:
    - '#dd7878'
  unstagedChangesColor:
    - '#d20f39'
  defaultFgColor:
    - '#4c4f69'
  searchingActiveBorderColor:
    - '#df8e1d'

authorColors:
  '*': '#8839ef'
